[package]
name = "example"
version = "0.1.0"
authors = ["Adam Becker <apbecker@protonmail.com>"]
edition = "2021"

[dependencies]
libretro-rs = { path = "../libretro-rs", features = ["experimental"] }

[lib]
crate-type = ["cdylib"]
